apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutor-api
  namespace: tutor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tutor-api
  template:
    metadata:
      labels:
        app: tutor-api
    spec:
      containers:
        - name: tutor-api
          image: docker_user_name/tutor-api:1.1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: tutor
spec:
  selector:
    app: tutor-api
  ports:
    - port: 8080
      targetPort: 8080
