#======================
#Namespace
#======================
apiVersion: v1
kind: Namespace
metadata:
  name: prod-demo
  labels:
    name: prod-demo

#==========================
#Deployment
#==========================
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
  namespace: prod-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      containers:
        - name: springbootapp
          image: 627821/helloworld:latest
          ports:
            - containerPort: 8080
          # Liveness & Readiness Probes
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          # Resource Limits
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"


#==========================
#Service
#==========================
---

apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: prod-demo
spec:
  selector:
    app: springbootapp
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

#=============================
#HorizontalPodAutoscaler
#=============================
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springbootapp-hpa
  namespace: prod-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: springbootapp
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

